# Generated by Django 5.2.17 on 2026-09-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calories_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calories per 100g.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fiber_g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dietary fiber in grams per 100g.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='potassium_mg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Potassium in milligrams per 100g.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vitamin_c_mg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vitamin C in milligrams per 100g.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vitamin_e_mg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vitamin E in milligrams per 100g.', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card / POS'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], max_length=30),
        ),
    ]
